package ru.mertsalovda.smsactivateapp.utils

import ru.mertsalovda.smsactivateapp.ui.activateflow.services.ServiceItem
import ru.sms_activate.response.api_activation.extra.SMSActivateGetPriceInfo

private val mapOfServices = mapOf(
    "vk" to "Вконтакте",
    "ok" to "Одноклассники",
    "wa" to "Whatsapp",
    "vi" to "Viber",
    "tg" to "Telegram",
    "wb" to "WeChat",
    "go" to "Google,youtube,Gmail",
    "av" to "avito",
    "av" to "avito + переадресация",
    "fb" to "facebook",
    "tw" to "Twitter",
    "ot" to "Любой другой + переадресация",
    "ub" to "Uber",
    "qw" to "Qiwi",
    "gt" to "Gett",
    "sn" to "OLX",
    "ig" to "Instagram",
    "ss" to "Hezzl",
    "ym" to "Юла",
    "ym" to "Юла + переадресация",
    "ma" to "Mail.ru",
    "mm" to "Microsoft",
    "uk" to "Airbnb",
    "me" to "Line messenger",
    "mb" to "Yahoo",
    "we" to "ДругВокруг",
    "bd" to "Пятерочка",
    "kp" to "HQ Trivia",
    "dt" to "Delivery Club",
    "ya" to "Яндекс",
    "ya" to "Яндекс + переадресация",
    "mt" to "Steam",
    "oi" to "Tinder",
    "fd" to "Mamba, MeetMe",
    "zz" to "Dent",
    "kt" to "KakaoTalk",
    "pm" to "AOL",
    "tn" to "LinkedIN",
    "qq" to "Tencent QQ",
    "mg" to "Магнит",
    "pf" to "pof.com",
    "yl" to "Yalla",
    "kl" to "kolesa.kz",
    "po" to "premium.one",
    "nv" to "Naver",
    "nf" to "Netflix",
    "iq" to "icq",
    "ob" to "Onlinerby",
    "kb" to "kufarby",
    "im" to "Imo",
    "mc" to "Michat",
    "ds" to "Discord",
    "vv" to "Seosprint",
    "ji" to "Monobank",
    "lf" to "TikTok/Douyin",
    "hu" to "Ukrnet",
    "wg" to "Skout",
    "rz" to "EasyPay",
    "vf" to "Q12 Trivia",
    "ny" to "Pyro Music",
    "rr" to "Wolt",
    "fe" to "CliQQ",
    "la" to "ssoidnet",
    "zh" to "Zoho",
    "gp" to "Ticketmaster",
    "am" to "Amazon",
    "ly" to "Olacabs",
    "tc" to "Rambler",
    "dp" to "ProtonMail",
    "pg" to "NRJ Music Awards",
    "yf" to "Citymobil",
    "op" to "MIRATORG",
    "fx" to "PGbonus",
    "qr" to "MEGA",
    "yk" to "СпортМастер",
    "ls" to "Careem",
    "bl" to "BIGO LIVE",
    "mu" to "MyMusicTaste",
    "fu" to "Snapchat",
    "bf" to "Keybase",
    "sg" to "OZON",
    "uu" to "Wildberries",
    "ua" to "BlaBlaCar",
    "ab" to "Alibaba",
    "iv" to "Inboxlv",
    "zy" to "Nttgame",
    "gd" to "Surveytime",
    "fy" to "Mylove",
    "ce" to "mosru",
    "tl" to "Truecaller",
    "hm" to "Globus",
    "tx" to "Bolt",
    "ka" to "Shopee",
    "pl" to "Перекресток",
    "ip" to "Burger King",
    "cm" to "Prom",
    "hw" to "AliPay",
    "de" to "Karusel",
    "jc" to "IVI",
    "rl" to "inDriver",
    "df" to "Happn",
    "ui" to "RuTube",
    "up" to "Magnolia",
    "nz" to "Foodpanda",
    "kf" to "Weibo",
    "ri" to "BillMill",
    "cc" to "Quipp",
    "lr" to "Okta",
    "za" to "JDcom",
    "da" to "MTS CashBack",
    "ug" to "Fiqsy",
    "sq" to "KuCoinPlay",
    "zr" to "Papara",
    "xv" to "Wish",
    "cx" to "Icrypex",
    "cw" to "PaddyPower",
    "li" to "Baidu",
    "dz" to "Dominos Pizza",
    "xz" to "paycell",
    "rd" to "Lenta",
    "qb" to "Payberry",
    "hz" to "Drom",
    "gl" to "GlobalTel",
    "zk" to "Deliveroo",
    "ia" to "Socios",
    "xl" to "Wmaraci",
    "yi" to "Yemeksepeti",
    "ew" to "Nike",
    "ae" to "myGLO",
    "gb" to "YouStar",
    "cy" to "РСА",
    "qm" to "RosaKhutor",
    "dh" to "eBay",
    "yb" to "Квартплата+",
    "qe" to "GG",
    "yw" to "Grindr",
    "uz" to "OffGamers",
    "gx" to "Hepsiburadacom",
    "re" to "Coinbase",
    "tj" to "dbrUA",
    "ts" to "PayPal",
    "rt" to "hily",
    "sf" to "SneakersnStuff",
    "sv" to "Dostavista",
    "qi" to "32red",
    "bz" to "Blizzard",
    "db" to "ezbuy",
    "vw" to "CoinField",
    "zl" to "Airtel",
    "wf" to "YandexGo",
    "lw" to "MrGreen",
    "co" to "Rediffmail",
    "ey" to "miloan",
    "ge" to "Paytm",
    "os" to "Dhani",
    "ql" to "CMTcuzdan",
    "cq" to "Mercado",
    "xk" to "DiDi",
    "py" to "Monese",
    "rv" to "Kotak811",
    "jl" to "Hopi",
    "pr" to "Trendyol",
    "pu" to "Justdating",
    "dk" to "Pairs",
    "fm" to "Touchance",
    "ph" to "SnappFood",
    "sw" to "NCsoft",
    "nr" to "Tosla",
    "hy" to "Ininal",
    "tr" to "Paysend",
    "pq" to "CDkeys",
    "ff" to "AVON",
    "sd" to "dodopizza",
    "ry" to "McDonalds",
    "le" to "E bike Gewinnspiel",
    "hr" to "JKF",
    "qa" to "MyFishka",
    "wc" to "Craigslist",
    "kw" to "Foody",
    "jg" to "Grab",
    "mj" to "Zalo",
    "eu" to "LiveScore",
    "ll" to "888casino",
    "ed" to "Gamer",
    "pp" to "Huya",
    "th" to "WestStein",
    "xr" to "Tango",
    "iz" to "Global24",
    "tk" to "МВидео",
    "rx" to "Sheerid",
    "ki" to "99app",
    "my" to "CAIXA",
    "zm" to "OfferUp",
    "tq" to "Swvl",
    "au" to "Haraj",
    "ei" to "Taksheel",
    "rp" to "hamrahaval",
    "pa" to "Gamekit",
    "fs" to "Şikayet var",
    "ul" to "Getir",
    "cf" to "irancell",
    "bt" to "Alfa",
    "ud" to "Disney Hotstar",
    "qu" to "Agroinform",
    "un" to "humblebundle",
    "rm" to "Faberlic",
    "uo" to "CafeBazaar",
    "ti" to "cryptocom",
    "nk" to "Gittigidiyor",
    "jm" to "mzadqatar",
    "lp" to "Algida",
    "si" to "Cita Previa",
    "fj" to "Potato Chat",
    "pt" to "Bitaqaty",
    "qc" to "Праймериз 2020",
    "yo" to "Amasia",
    "fx" to "PGbonus + переадресация",
    "ve" to "Dream11",
    "qh" to "Oriflame",
    "iu" to "Bykea",
    "ib" to "Immowelt",
    "zv" to "Digikala",
    "jb" to "Wing Money",
    "vn" to "Yaay",
    "wn" to "GameArena",
    "bj" to "Вита экспресс",
    "st" to "Auchan",
    "ev" to "Picpay",
    "qn" to "Blued",
    "cd" to "SpotHit",
    "vo" to "Brand20ua",
    "il" to "IQOS",
    "dx" to "Powerkredite",
    "el" to "Bisu",
    "dn" to "Paxful",
    "lk" to "PurePlatfrom",
    "vc" to "Banqi",
    "wj" to "1хbet",
    "wk" to "Mobile01",
    "jj" to "Aitu",
    "an" to "Adidas",
    "jr" to "Самокат",
    "nb" to "Верный",
    "gv" to "Humta",
    "dw" to "Divar",
    "gj" to "Carousell",
    "hc" to "MOMO",
    "uf" to "Eneba",
    "kn" to "Verse",
    "qd" to "Taobao",
    "hn" to "1688",
    "zf" to "OnTaxi",
    "gi" to "Hotline",
    "uc" to "Tatneft",
    "ot" to "Любой другой",
)

fun String.toServiceName(): String? {
    return mapOfServices[this]
}

fun MutableMap<String, SMSActivateGetPriceInfo>.toServiceItem(): List<ServiceItem> {
    val result = mutableListOf<ServiceItem>()
    for ((key, value) in this) {
        if (!key.endsWith("_1")) {
            result.add(
                ServiceItem(
                    image = key.getServiceImageUrl(),
                    codeName = key,
                    displayName = key.toServiceName() ?: "",
                    count = value.countPhoneNumbers,
                    cost = value.cost
                )
            )
        }
    }
    return result
}

fun Int.getCountryImageUrl() = "https://sms-activate.ru/assets/ico/country/${this}.png"
fun String.getServiceImageUrl() = "https://sms-activate.ru/assets/ico/${this}0.png"